// Login types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS';

// Signup types
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_SUCCESSFULL = 'SIGNUP_SUCCESSFULL';

// Get Notes types
export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST';
export const GET_NOTES_FAILED = 'GET_NOTES_FAILED';
export const GET_NOTES_SUCCESSFULL = 'GET_NOTES_SUCCESSFULL';

// Add Note types
export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST';
export const ADD_NOTE_FAILED = 'ADD_NOTE_FAILED';
export const ADD_NOTE_SUCCESSFULL = 'ADD_NOTE_SUCCESSFULL';

// Get Single Note types
export const GET_SINGLE_NOTE_REQUEST = 'GET_SINGLE_NOTE_REQUEST';
export const GET_SINGLE_NOTE_FAILED = 'GET_SINGLE_NOTE_FAILED';
export const GET_SINGLE_NOTE_SUCCESSFULL = 'GET_SINGLE_NOTE_SUCCESSFULL';

// Update Note types
export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST';
export const UPDATE_NOTE_FAILED = 'UPDATE_NOTE_FAILED';
export const UPDATE_NOTE_SUCCESSFULL = 'UPDATE_NOTE_SUCCESSFULL';


// Delete Note types
export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST';
export const DELETE_NOTE_FAILED = 'DELETE_NOTE_FAILED';
export const DELETE_NOTE_SUCCESSFULL = 'DELETE_NOTE_SUCCESSFULL';

// Logout
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
